src/Web/FMCApp.Web/Models/ViewModels/VisualizationModels/Movies/AllMoviesViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FMCApp.Data.Models;

namespace FMCApp.Web.Models.ViewModels.VisualizationModels.Movies
{
    public class AllMoviesViewModel
    {
        public AllMoviesViewModel()
        {
            this.Movies = new HashSet<MoviesViewModel>();
        }

        public IEnumerable<MoviesViewModel> Movies { get; set; }
    }
}

src/Web/FMCApp.Web/Controllers/DirectorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FMCApp.Data;
using FMCApp.ViewModels.ViewModels.VisualizationModels.Directors;
using Microsoft.AspNetCore.Mvc;

namespace FMCApp.Web.Controllers
{
    public class DirectorsController : Controller
    {
        private readonly FMCAppContext _context;

        public DirectorsController(FMCAppContext context)
        {
            _context = context;
        }

        public IActionResult Details(string directorName)
        {
            var directorExist = this._context.Directors.FirstOrDefault(d => d.Name == directorName);
            if (directorExist == null)
            {
                return NotFound();
            }

            var directorModel = this._context.Directors.Select(d => new DirectorViewModel
            {
                Name = d.Name,
                Info = d.Info,
                BirthDate = d.Birthdate
            }).FirstOrDefault(d => d.Name == directorName);

            return this.View(directorModel);
        }
    }
}

src/Web/FMCApp.Web/Controllers/MoviesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using FMCApp.Data;
using FMCApp.Data.Models;
using FMCApp.Services.Interfaces;
using FMCApp.Web.Models.ViewModels.VisualizationModels.Comments;
using FMCApp.Web.Models.ViewModels.VisualizationModels.Movies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using X.PagedList;

namespace FMCApp.Web.Controllers
{
    public class MoviesController : Controller
    {
        private readonly FMCAppContext _context;
        private readonly UserManager<FMCAppUser> _userManager;
        private readonly IMovieService _movieService;
        public MoviesController(FMCAppContext context, UserManager<FMCAppUser> userManager, IMovieService movieService)
        {
            _context = context;
            _userManager = userManager;
            _movieService = movieService;
        }

        public async Task<IActionResult> AllMovies(int? pageNumber, string searchString)
        {

            var movie = this._context.Movies.OrderByDescending(m => m.Id).Select(m => new MoviesViewModel
            {
                Id = m.Id,
                Title = m.Title,
                MoviePosterUrl = m.MoviePosterUrl
            });
            var moviesModel = new AllMoviesViewModel
            {
                 Movies = movie
            };
            var nextPage = pageNumber ?? 1;
            var pagedViewModel = moviesModel.Movies.ToPagedList(nextPage, 6);

           

            if (!String.IsNullOrEmpty(searchString))
            {
                movie = movie.Where(s => s.Title.Contains(searchString));
                return View("SearchMovie",await movie.ToListAsync());
            }

            return this.View(pagedViewModel);
            //  return this.View(moviesModel);

        }

        public IActionResult Details(int? id)
        {
            //var movieCheck = this._context.Movies.Find(id);
            //if (movieCheck == null)
            //{
            //    return NotFound();
            //}

            //var movie = this._context.Movies.Select(m => new MovieDetailsViewModel
            //{
            //    Id = m.Id,
            //    Title = m.Title,
            //    Director = m.Director.Name,
            //    Description = m.Description,
            //    Genre = m.Genre.ToString(),
            //    ReleaseDate = m.ReleaseDate,
            //    MoviePosterUrl = m.MoviePosterUrl,


            //}).FirstOrDefault(m => m.Id == id);
            var movieModel = this._movieService.GetAllMoviesModel(id);
            return View("Details",movieModel); // TODO : Implement view correctly ! ! ! !
        }

       
        //[Authorize]
        [HttpPost]
        public IActionResult AddToWatchlist(int id)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return this.RedirectToAction("Register", "Users");
            }
            var movieObject = this._context.Movies.FirstOrDefault(m => m.Id == id);
            if (movieObject == null)    
            {
                return this.NotFound();
            }

            string userId = this._userManager.GetUserId(HttpContext.User);
            var user = this._context.Users.FirstOrDefault(u => u.Id == userId);
            if (user == null)
            {
                return this.RedirectToAction("Register", "Users");
            }

        
            var watchlist = new WatchList
            {
                AddedOn = DateTime.UtcNow,
                FmcAppUser = user,
                Movie = movieObject

            };
            var movieModel = this._context.Movies.Select(m => new MovieDetailsViewModel
            {
                Id = m.Id,
                Title = m.Title,
                Director = m.Director.Name,
                Description = m.Description,
                Genre = m.Genre.ToString(),
                ReleaseDate = m.ReleaseDate,
                MoviePosterUrl = m.MoviePosterUrl,


            }).FirstOrDefault(m => m.Id == id);
            var duplcateChecker = this._context.WatchLists.Any(c => c.UserId == userId && c.MovieId == movieObject.Id);
            if (duplcateChecker)
            {
                ViewBag.message = "Already Added";
                return this.View("Details", movieModel);

            }
            this._context.Add(watchlist);
            this._context.SaveChanges();
            return this.View("Details", movieModel);
        }
    }
}

src/Web/FMCApp.Web/Views/Movies/AllMovies.cshtml
@using X.PagedList
@using X.PagedList.Mvc.Common
@using X.PagedList.Mvc.Core
@{
    ViewData["Title"] = "AllMovies";
}
@model IEnumerable<FMCApp.Web.Models.ViewModels.VisualizationModels.Movies.MoviesViewModel>
<div id="gallery" class="tm-content-box">
    <div class="grid tm-gallery">   
        @foreach(var movie in @Model)
        { 
            <figure class="effect-bubba">
                <img src="@movie.MoviePosterUrl" alt="Image 8" class="img-fluid" />
                <figcaption>
                    <h4><span>@movie.Title</span></h4>
                    <a asp-controller="Movies" asp-action="Details" asp-route-id="@movie.Id"></a>
                </figcaption>
            </figure>
        }
    </div>
    @Html.PagedListPager((IPagedList)Model, pageNumber => Url.Action("AllMovies", new { pageNumber }),new PagedListRenderOptions
    {
        LiElementClasses = new string[] { "page-item" },
        PageClasses = new string[] { "page-link" },
        DisplayLinkToFirstPage = 0,
        DisplayLinkToLastPage = 0,
     
        
    })

</div>

src/Web/FMCApp.Web/Views/Movies/Details.cshtml
@{
    ViewData["Title"] = "Details";
}

@model FMCApp.Web.Models.ViewModels.VisualizationModels.Movies.MovieDetailsViewModel
    <div class="card">
        <div class="row">
            <aside class="col-sm-5 border-right">
                <article class="gallery-wrap">
                    <div class="img-big-wrap">
                        <div>
                            <img src="@Model.MoviePosterUrl" width="380" height="700" class="img-responsive">
                        </div>
                    </div> <!-- slider-product.// -->
                </article> <!-- gallery-wrap .end// -->
            </aside>
            <aside class="col-sm-7">
                <article class="card-body p-5">
                    <h3 class="title mb-3">@Model.Title</h3>
          
                    <hr style="background-color: black">
                    <dl class="item-property">
                        <dt>Genre:</dt>
                        <dd>
                            <p>@Model.Genre</p>
                        </dd>
                    </dl>
                    <dl class="item-property">
                        <dt>Description:</dt>
                        <dd>
                            <p>
                                @Model.Description
                            </p>
                        </dd>
                    </dl>
                    <dl class="param param-feature">
                        <dt>Release Date:</dt>
                        <dd>@Model.ReleaseDate.Value.ToShortDateString() @Model.ReleaseDate.Value.Year</dd>
                    </dl>
                    <dl class="param param-feature">
                        <dt>Director:</dt>
                        <dd> <a asp asp-controller="Directors" asp-action="Details" asp-route-directorName="@Model.Director" >@Model.Director</a></dd>
                    </dl>  <!-- item-property-hor .// -->
                    <hr />
                    @if (!string.IsNullOrEmpty(ViewBag.message))
                    {
                        <button type="button" class="btn btn-lg btn-info-outline-outline text-uppercase" disabled>@ViewBag.message</button>
                    }
                    <form asp-controller="Movies" asp-action="AddToWatchlist" asp-route-id="@Model.Id" method="post">
                        <button type="submit" id="addToWatchlist" class="btn btn-lg btn-success text-uppercase">+ Add to Watchlist</button>
                    </form>
                    <a asp-controller="UserReviews" asp-action="Comments" asp-route-id="@Model.Id" class="btn btn-lg btn-info text-uppercase">User Reviews</a>
                </article> <!-- card-body.// -->
            </aside> <!-- col.// -->
        </div> <!-- row.// -->
    </div> <!-- card.// -->
<!--container.//-->
@*@section Scripts
{
    <script>
        document.getElementById('addToWatchlist').onclick = function() {
            document.getElementById('removeFromWatchlist').style.display = "block";
            document.getElementById('addToWatchlist').style.display = "none";
        }
        document.getElementById('removeFromWatchlist').onclick = function() {
        }
        document.getElementById('removeFromWatchlist').style.display = "none";
        document.getElementById('addToWatchlist').style.display = "block";
    </script>
}*@

src/Web/FMCApp.Web/Views/Movies/SearchMovie.cshtml
@{
    ViewData["Title"] = "SearchMovie";
}

<h2>SearchMovie</h2>

@using X.PagedList
@using X.PagedList.Mvc.Common
@using X.PagedList.Mvc.Core
@model IEnumerable<FMCApp.Web.Models.ViewModels.VisualizationModels.Movies.MoviesViewModel>
<div id="gallery" class="tm-content-box">
    <div class="grid tm-gallery">
        @foreach (var movie in @Model)
        {
            <figure class="effect-bubba">
                <img src="@movie.MoviePosterUrl" alt="Image 8" class="img-fluid" />
                <figcaption>
                    <h4><span>@movie.Title</span></h4>
                    <a asp-controller="Movies" asp-action="Details" asp-route-id="@movie.Id"></a>
                </figcaption>
            </figure>
        }
    </div>
</div>