src/Web/FMCApp.Web/Controllers/ChatsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace FMCApp.Web.Controllers
{
    [Authorize]
    public class ChatsController : Controller
    {
        public IActionResult OpenChat()
        {
            return View();
        }
    }
}

src/Web/FMCApp.Web/Controllers/MoviesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using FMCApp.Data;
using FMCApp.Data.Models;
using FMCApp.Services.Interfaces;
using FMCApp.Web.Models.ViewModels.VisualizationModels.Comments;
using FMCApp.Web.Models.ViewModels.VisualizationModels.Movies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using X.PagedList;

namespace FMCApp.Web.Controllers
{
    public class MoviesController : Controller
    {
        private readonly FMCAppContext _context;
        private readonly UserManager<FMCAppUser> _userManager;
        private readonly IMovieService _movieService;
        public MoviesController(FMCAppContext context, UserManager<FMCAppUser> userManager, IMovieService movieService)
        {
            _context = context;
            _userManager = userManager;
            _movieService = movieService;
        }

        public async Task<IActionResult> AllMovies(int? pageNumber, string searchString)
        {

            var movie = this._context.Movies.OrderByDescending(m => m.Id).Select(m => new MoviesViewModel
            {
                Id = m.Id,
                Title = m.Title,
                MoviePosterUrl = m.MoviePosterUrl
            });
            var moviesModel = new AllMoviesViewModel
            {
                 Movies = movie
            };
            var nextPage = pageNumber ?? 1;
            var pagedViewModel = moviesModel.Movies.ToPagedList(nextPage, 6);

           

            if (!String.IsNullOrEmpty(searchString))
            {
                movie = movie.Where(s => s.Title.Contains(searchString));
                return View("SearchMovie",await movie.ToListAsync());
            }

            return this.View(pagedViewModel);
            //  return this.View(moviesModel);

        }

        public IActionResult Details(int? id)
        {
            //var movieCheck = this._context.Movies.Find(id);
            //if (movieCheck == null)
            //{
            //    return NotFound();
            //}

            //var movie = this._context.Movies.Select(m => new MovieDetailsViewModel
            //{
            //    Id = m.Id,
            //    Title = m.Title,
            //    Director = m.Director.Name,
            //    Description = m.Description,
            //    Genre = m.Genre.ToString(),
            //    ReleaseDate = m.ReleaseDate,
            //    MoviePosterUrl = m.MoviePosterUrl,


            //}).FirstOrDefault(m => m.Id == id);
            var movieModel = this._movieService.GetAllMoviesModel(id);
            return View("Details",movieModel); // TODO : Implement view correctly ! ! ! !
        }

       
        //[Authorize]
        [HttpPost]
        public IActionResult AddToWatchlist(int id)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return this.RedirectToAction("Register", "Users");
            }
            var movieObject = this._context.Movies.FirstOrDefault(m => m.Id == id);
            if (movieObject == null)    
            {
                return this.NotFound();
            }

            string userId = this._userManager.GetUserId(HttpContext.User);
            var user = this._context.Users.FirstOrDefault(u => u.Id == userId);
            if (user == null)
            {
                return this.RedirectToAction("Register", "Users");
            }

        
            var watchlist = new WatchList
            {
                AddedOn = DateTime.UtcNow,
                FmcAppUser = user,
                Movie = movieObject

            };
            var movieModel = this._context.Movies.Select(m => new MovieDetailsViewModel
            {
                Id = m.Id,
                Title = m.Title,
                Director = m.Director.Name,
                Description = m.Description,
                Genre = m.Genre.ToString(),
                ReleaseDate = m.ReleaseDate,
                MoviePosterUrl = m.MoviePosterUrl,


            }).FirstOrDefault(m => m.Id == id);
            var duplcateChecker = this._context.WatchLists.Any(c => c.UserId == userId && c.MovieId == movieObject.Id);
            if (duplcateChecker)
            {
                ViewBag.message = "Already Added";
                return this.View("Details", movieModel);

            }
            this._context.Add(watchlist);
            this._context.SaveChanges();
            return this.View("Details", movieModel);
        }
    }
}

src/Web/FMCApp.Web/Controllers/NewsController.cs
using System.Collections.Generic;
using System.Linq;
using FMCApp.Data;
using FMCApp.Services.Interfaces;
using FMCApp.Web.Models.ViewModels.VisualizationModels.News;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Internal;
using  X.PagedList;
namespace FMCApp.Web.Controllers
{
    public class NewsController : Controller
    {
        private readonly FMCAppContext _context;
        private readonly INewsService _newsService;
        public NewsController(FMCAppContext context, INewsService newsService)
        {
            _context = context;
            _newsService = newsService;
        }

        public IActionResult AllNews(int? pageNumber)
        {

            var news = this._newsService.GetAllNews();
            var newsesModel = new AllNewsesViewModel
            {
                Newses = news
            };
            var nextPage = pageNumber ?? 1;
            var pagedViewModel = newsesModel.Newses.ToPagedList(nextPage,3);
            return this.View(pagedViewModel);

        }

        public IActionResult Details(int? id)
        {
            //var news = this._context.Newses.Find(id);
            //if (news == null)
            //{
            //    return NotFound();
            //}
            
            //var newsModel = this._context.Newses.Select(n => new NewsDetailsViewModel
            //{
            //     Id = n.Id,
            //     Content = n.Content,
            //    Title = n.Title,
            //    ImageUrl = n.ImageUrl
            //}).FirstOrDefault(n => n.Id == id);
            var newsModel = this._newsService.GetModel(id);
            return View("Details",newsModel);
        }
    }
}

src/Web/FMCApp.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>

    <link href="~/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/css/magnific-popup.css" rel="stylesheet" />
    <link href="~/css/templatemo-style.css" rel="stylesheet" />
    <link href="~/css/site.css" rel="stylesheet" />
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">

  
</head>
<body style="background-color:#d4d4d4">
<div class="container-fluid">

    <div id="welcome" class="tm-content-box tm-banner margin-b-10">
        <div class="tm-banner-inner">
            <h1 class="tm-banner-title">FAVOURITE MOVIES COLLECTION</h1>
        </div>
    </div>
    <div class="tm-body">
        <div class="tm-sidebar">
            <nav class="tm-main-nav">
                <ul class="tm-main-nav-ul">
                    @if (!User.Identity.IsAuthenticated)
                    {

                        <li class="tm-nav-item">
                            <a class="tm-nav-item-link tm-button" asp-controller="Users" asp-action="Login">Login</a>
                        </li>

                        <li class="tm-nav-item">
                            <a class="tm-nav-item-link tm-button" asp-controller="Users" asp-action="Register">Register</a>
                        </li>
                    }
                    else
                    {
                        <li class="tm-nav-item">
                            <a class="tm-nav-item-link tm-button" asp-controller="Users" asp-action="Logout">Logout</a>
                        </li>
                        <li class="tm-nav-item">
                            <a class="tm-nav-item-link tm-button" asp-controller="Chats" asp-action="OpenChat">Open Chat</a>
                        </li>
                        <li class="tm-nav-item">
                            <a class="tm-nav-item-link tm-button" asp-controller="Users" asp-action="Watchlist">Your Watchlist</a>
                        </li>
                        <li class="tm-nav-item">
                            <a class="tm-nav-item-link tm-button" asp-controller="Users" asp-action="Comments">Commented Моvies</a>
                        </li>
                    }
                    <li class="tm-nav-item">
                        <a class="tm-nav-item-link tm-button" asp-controller="News" asp-action="AllNews">Movie News</a>
                    </li>
                    <li class="tm-nav-item">
                        <a class="tm-nav-item-link tm-button" asp-controller="Movies" asp-action="AllMovies">Movies</a>
                    </li>
                  
                    <li class="tm-nav-item">
                        <a asp-controller="Home" asp-action="Index" class="tm-nav-item-link tm-button">
                            Welcome
                        </a>
                    </li>
                </ul>
            </nav>
         
            @if (User.Identity.IsAuthenticated && this.User.IsInRole("Administrator"))
            {
                <li class="tm-nav-item">
                    <a asp-controller="Administrators" asp-action="AllUsers" asp-area="Administration" class="tm-nav-item-link tm-button">
                        All Users
                    </a>
                </li>
                <li class="tm-nav-item">
                    <a asp-controller="Administrators" asp-action="AddMovie" asp-area="Administration" class="tm-nav-item-link tm-button">
                        Add Movie
                    </a>
                </li>

            }
          
            <div>
                <form asp-controller="Movies" asp-action="AllMovies" method="get">
                    <p  class="tm-nav-item-link tm-button">
                        Title: <input type="text" class="bg-dark" name="SearchString">
                        <input type="submit" value="Search" class="tm-purple-bg" />
                    </p>
                </form>
            </div>
        </div>
        
        @RenderBody()
    </div>
</div>
<hr />
<footer>
    <p>&copy; 2018 - FMCApp.Web</p>
</footer>


<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/@@aspnet/signalr/dist/browser/signalr.min.js"></script>
<script src="~/js/site.js" asp asp-append-version="true"></script>
@RenderSection("Scripts", required: false)
</body>
</html>